apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-jib-demo
  name: springboot-jib-demo
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32693
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: springboot-jib-demo
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-jib-demo
  labels:
    app: springboot-jib-demo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: springboot-jib-demo
  template:
    metadata:
      labels:
        app: springboot-jib-demo
    spec:
      containers:
        - name: jib-demo
          image: gcr.io/xylia-platform/springboot-jib-demo:latest

          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5

          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5

          resources:
            requests:
              memory: "800M"
              cpu: "100m"
            limits:
              memory: "900M"
              cpu: "250m"
          env:
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
